### ISSUE TITLE
Postgrsql 9.4 and page sizes

### ISSUE THREAD

**Issue by simovesterinen** [knizhnik/imcs#41]
Hi,

Now Postgresql has published version 9.4 and that supports huge page sizes. Doesn't that allow better configuration options for IMCS? 
Doesn't enable allow better use for skip indexes for example?

How about using IMCS with 9.4. Do you know does IMCS work with 9.4?

Any comments?

-Simo

**Comment by knizhnik** [comment]
Hi,

Support of huge pages in PostgreSQL just simplify IMCS usage - there is no need any more to patch PostgreSQL code to use huge pages and so use more than 256Gb of memory.
Yes, IMCS works with 9.4

**Comment by simovesterinen** [comment]
Thanks for your answer :)
