### ISSUE TITLE
Installing imcs with apt repo postgres

### ISSUE THREAD

**Issue by simovesterinen** [knizhnik/imcs#43]
Hi,

Is it possible to install imcs to postgresql which is installed from ubuntu apt repo using sudo apt-get install postgresql?
What kind of changes are needed to files to achieve this?

I'm using postgresql 9.4 and I would like to switch my postgresql version from source code to apt repo version.

**Comment by knizhnik** [comment]
Hi,

IMCS can be built and installed as any other PostgreSQL extension.
You need to have PostgreSQL sources for it (actually only include files).
It means that you should install |postgresql-devel| or |postgresql-dev| packages.
So there is no need to change something in PostgreSQL or IMCS, what you need is just presence of PostgreSQL header files.


On 04/02/2015 08:23 AM, simovesterinen wrote:
>
> Hi,
>
> Is it possible to install imcs to postgresql which is installed from ubuntu apt repo using sudo apt-get install postgresql?
> What kind of changes are needed to files to achieve this?
>
> I'm using postgresql 9.4 and I would like to switch my postgresql version from source code to apt repo version.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/knizhnik/imcs/issues/43>.
>


-- 
Best regards,
Konstantin
