### ISSUE TITLE
Cannot install repo with latest commit (cs_win_group_* functions)

### ISSUE THREAD

**Issue by pavitrakumar78** [knizhnik/imcs#63]
Hi,

I just got some time and wanted to start experimenting with the cs_win_* functions so I decided to clone a fresh copy of the imcs but I'm not able to install the extension in pgsql.

The installation of extension by using `install.sh` works, but when adding extension by using `create extension imcs;` I get this error:
```
ERROR:  could not find function "cs_win_group_max" in file "/usr/lib/postgresql/12/lib/imcs.so"
```

I tried checking out till before the last commit (`git checkout ab4ec5e84d903b956a8a127a684e8b589a475822 --force`) and was able to install and add to pgsql without any issues.

**Comment by knizhnik** [comment]
Sorry, this error ERROR:  could not find function "cs_win_group_max" in file "/usr/lib/postgresql/12/lib/imcs.so"
means that you are using old version of the library. Please check that extension is properly installed.
Just check the date of /usr/lib/postgresql/12/lib/imcs.so file

**Comment by pavitrakumar78** [comment]
I tried using a fresh clone (`git clone https://github.com/knizhnik/imcs`) and also manually deleted the file from pgsql lib to make sure a new .so file is added

![image](https://user-images.githubusercontent.com/5354407/101496540-e6c97100-398f-11eb-8dbb-d245c670ff28.png)

Still, the result is the same. This has not happened before (when updating imcs from source repo).

**Comment by knizhnik** [comment]
Please check that you have restarted postgres and there are no other instances of postgres using IMCS library.
If it doesn't help, please show how you are building and installing IMCS extension.

**Comment by pavitrakumar78** [comment]
Ahhh! Forgot the restart psgsql instance part! That's embarrassing... 
Sorry! Thank you for the help!
