### ISSUE TITLE
Row insertion for symbols not reflected in imcs table unless server is restarted

### ISSUE THREAD

**Issue by pavitrakumar78** [knizhnik/imcs#68]
Hi,

I'm having an issue where simple cs_* functions on a loaded table does not return updated values when the underlying pgsql table from which the imcs table is created is updated.

Here's a full sample dump of simple example: https://pastebin.com/FD9C0XLF
A short explanation of what I'm trying to do in the example: 
-A table (pgsql base) has 5 rows of AAPL stock values (2020-01-01 to 2020-01-05)
-I use `cs_tail` to get the last date using `us_eod_test_get` and it returns `2020-01-05` correctly
-Now I add another AAPL row with rate 2020-01-06
-I use `cs_tail` again and still get `2020-01-05` which is wrong.

I'm using the latest imcs version and also restarted server several times before and after install. 

The only way so far (that I've found) is to restart the server. After restarting the server, the same `cs_tail` query will return the correct result. 

Is this a problem with triggers not working properly?

**Comment by knizhnik** [comment]
You have called cs_create with disable "autoupdate" parameter (default).
In this case on update triggers are disabled.

**Comment by pavitrakumar78** [comment]
> You have called cs_create with disable "autoupdate" parameter (default).
> In this case on update triggers are disabled.

Thank you! That was it!

**Comment by pavitrakumar78** [comment]
I was reading the docs and found this in the `autoupdate` param explanation:
```
Please notice that explicit bulk update/delete is significantly more efficient than row-level updated performed by trigger.
```
Can you please expand a bit on this? explicit bulk update meaning on the original underlying table right? Is this implying that when data is added - say, 10k rows added and deleted everyday, it's better to just drop the imcs table and re-load it?

**Comment by knizhnik** [comment]
I do not mean rebuild table from scratch. When you use triggers, then record will be inserted in IMCS columnar store one-by-one. It is very very inefficient. Much better is to load group of records. If 10k records are added each day, then at the end of the day append this 10k records using *_load() function with correspondent filter (assuming that there is some monotonic key allowing to select new records)

**Comment by pavitrakumar78** [comment]
Thank you for the clarification! I don't see any examples of 'filter text' which a parameter in `function TABLE_load(already_sorted bool default false, filter text default null)`. Say, I want to add all rows with date 2021-02-11, 2021-02-10 for all symbols (unique symbol id column - such as the quotes table symbols), what should be the filter text input?

**Comment by knizhnik** [comment]
To load all data since 10 Februrary you can do something like this:
```
select Quote_load(filter:='date>=''2021-02-10''');
```
Certainly you can specify any other criteria, for example `date between '2021-02-10' and '2021-02-11'`

**Comment by pavitrakumar78** [comment]
Ah! Got it! Thank again! :)
