### ISSUE TITLE
table-level-locking on postgresql 12->

### ISSUE THREAD

**Issue by jukkave** [knizhnik/imcs#69]
Hi @knizhnik
 
Have you tested table-level-locking on PostgreSQL 12 or newer?

I can install the master branch (PostgreSQL 12, 13, 14 on Ubuntu 20.04) but not table-level-locking.

Errors are saying about FunctionCallInfoData.
"Writing a Procedural Language Handler" (based on this article https://www.postgresql.org/docs/12/plhandler.html) is updated from FunctionCallInfoData to FunctionCallInfoBaseData in 12 and newer.
And I see that change in master branch also.

Is it possible to get that update to "table-level-locking"?

**Comment by knizhnik** [comment]
Done

**Comment by jukkave** [comment]
@knizhnik Thank you a lot for really quick fix! Now installation was success!

There were couple warnings (postgresql 13 and 14). Are those anything to be concerned about?
```
gcc -O3 -Wall -Wno-format-security -fPIC -shared -o imcs.so imcs.o func.o smp.o btree.o threadpool.o -pthread  -lm
/usr/bin/clang-9 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -O3 -Wall -pthread -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o imcs.bc imcs.c
imcs.c:863:20: warning: implicit conversion from enumeration type 'enum LWLockMode' to different enumeration type 'imcs_lock_t' [-Wenum-conversion]
                imcs_dict_lock = LW_SHARED;
                               ~ ^~~~~~~~~
1 warning generated.
/usr/bin/clang-9 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -O3 -Wall -pthread -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o func.bc func.c
func.c:6206:30: warning: field 'fcinfo' with variable sized type 'FunctionCallInfoBaseData' (aka 'struct FunctionCallInfoBaseData') not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
    FunctionCallInfoBaseData fcinfo;
                             ^
1 warning generated.
```

**Comment by jukkave** [comment]
In PostgreSQL 14.1: when trying to create IMCS extension from "table-level-locking" branch I got an error.
```
--COMMAND
﻿CREATE EXTENSION IF NOT EXISTS imcs;
﻿--RESULT
/*
﻿﻿ERROR: operator right argument type must be specified﻿
﻿DETAIL: Postfix operators are not supported.
SQL state: 42P13
﻿*/
```
Again in "master" branch it works.
@knizhnik Is this also something that could be updated to "table-level-locking"?

**Comment by knizhnik** [comment]
Sorry, please try now

**Comment by jukkave** [comment]
Thanks again now it worked!
